name: Build Windows Executable

on:
  push:
    branches: [ main ]
    paths: 
      - 'standalone-whisper/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'standalone-whisper/**'
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: standalone-whisper
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create version info file
      shell: cmd
      run: |
        (
        echo VSVersionInfo^(
        echo   ffi=FixedFileInfo^(
        echo     filevers=^(1,0,0,0^),
        echo     prodvers=^(1,0,0,0^),
        echo     mask=0x3f,
        echo     flags=0x0,
        echo     OS=0x4,
        echo     fileType=0x1,
        echo     subtype=0x0,
        echo     date=^(0, 0^)
        echo     ^),
        echo   kids=[
        echo     StringFileInfo^([
        echo       StringTable^(u'040904B0', [
        echo         StringStruct^(u'CompanyName', u'MVP-Echo'^),
        echo         StringStruct^(u'FileDescription', u'MVP-Echo Standalone Whisper'^),
        echo         StringStruct^(u'FileVersion', u'1.0.0.0'^),
        echo         StringStruct^(u'InternalName', u'whisper-standalone'^),
        echo         StringStruct^(u'LegalCopyright', u'Copyright 2024 MVP-Echo'^),
        echo         StringStruct^(u'OriginalFilename', u'whisper-standalone.exe'^),
        echo         StringStruct^(u'ProductName', u'MVP-Echo Standalone Whisper'^),
        echo         StringStruct^(u'ProductVersion', u'1.0.0.0'^)
        echo       ]^)
        echo     ]^), 
        echo     VarFileInfo^([VarStruct^(u'Translation', [1033, 1200]^)]^)
        echo   ]
        echo ^)
        ) > version_info.py
    
    - name: Build Windows executable
      run: |
        python -m PyInstaller ^
          --onefile ^
          --name=whisper-standalone ^
          --distpath=dist ^
          --workpath=build ^
          --specpath=build ^
          --clean ^
          --noconfirm ^
          --console ^
          --hidden-import=faster_whisper ^
          --hidden-import=faster_whisper.transcribe ^
          --hidden-import=faster_whisper.vad ^
          --hidden-import=torch ^
          --hidden-import=ctranslate2 ^
          --hidden-import=tokenizers ^
          --hidden-import=huggingface_hub ^
          --hidden-import=numpy ^
          --hidden-import=onnxruntime ^
          --version-file=version_info.py ^
          --optimize=2 ^
          --log-level=WARN ^
          whisper-cli.py
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: whisper-standalone-windows
        path: standalone-whisper/dist/whisper-standalone.exe
        if-no-files-found: error
    
    - name: Test executable
      run: |
        dist\whisper-standalone.exe --version
    
    # Optional: Create release on tags
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    
    - name: Upload Release Asset
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: standalone-whisper/dist/whisper-standalone.exe
        asset_name: whisper-standalone.exe
        asset_content_type: application/octet-stream